# Generated by Django 4.2.7 on 2024-05-31 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academic_feedback_sys", "0002_alter_subject_subject"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"permissions": (("edit_student_grade", "update_student_grade"),)},
        ),
    ]
