# Generated by Django 4.2.7 on 2024-03-27 11:15

from django.db import migrations, models
import healthpass.models


class Migration(migrations.Migration):

    dependencies = [
        ("healthpass", "0005_appearance_bilirubin_blood_color_glucose_ketone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="urinalysis",
            name="ph",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="values in 1 decimal place e.g 1.0, 2.0, 2.5, and so on.",
                max_digits=2,
                null=True,
                validators=[healthpass.models.validate_ph_field],
            ),
        ),
        migrations.AlterField(
            model_name="urinalysis",
            name="specific_gravity",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="values in 3 decimal place e.g 0.001, 2.3456, and so on.",
                max_digits=4,
                null=True,
                validators=[healthpass.models.validate_specific_gravity_field],
            ),
        ),
        migrations.AlterField(
            model_name="urinalysis",
            name="urobilinogen",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="values in 1 decimal place e.g 2.3, 4.5, and so on.",
                max_digits=2,
                null=True,
                validators=[healthpass.models.validate_urobilinogen_field],
            ),
        ),
    ]
