# Generated by Django 4.2.7 on 2024-03-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthpass", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(max_length=300),
        ),
    ]
