# Generated by Django 4.2.7 on 2024-03-24 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import healthpass.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "healthpass",
            "0002_alter_customuser_email_alter_customuser_first_name_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BloodGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("AA", "blood_type_A"),
                            ("AO", "blood_type_A+o"),
                            ("BB", "blood_type_B"),
                            ("BO", "blood_type_B+o"),
                            ("AB", "blood_type_AB"),
                            ("OO", "blood_type_O"),
                        ],
                        max_length=2,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HbGenotype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hb_genotype",
                    models.CharField(
                        choices=[
                            ("AA", "no_haemoglobin_disorder"),
                            ("AS", "sickle_cell_trait"),
                            ("SS", "sickle_cell_disease"),
                            ("SC", "sickle_cell_haemoglobin_c_disease"),
                            ("CC", "haemoglobin_c_disease"),
                            ("AC", "sickle_cell_mutation"),
                        ],
                        max_length=2,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HepatitisA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hepatitis_a",
                    models.CharField(
                        choices=[("yes", "positive"), ("no", "negative")],
                        max_length=3,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HepatitisB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hepatitis_b",
                    models.CharField(
                        choices=[("yes", "positive"), ("no", "negative")],
                        max_length=3,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HIV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hiv",
                    models.CharField(
                        choices=[("yes", "positive"), ("no", "negative")],
                        max_length=3,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HPYLORI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hpylori",
                    models.CharField(
                        choices=[("yes", "positive"), ("no", "negative")],
                        max_length=3,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MalariaParasite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "malaria_parasite",
                    models.CharField(
                        choices=[("yes", "positive"), ("no", "negative")],
                        max_length=3,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RhesusAntigen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rhesus_antigen",
                    models.CharField(
                        choices=[
                            ("A+", "rhesus_positve_a"),
                            ("A-", "rhesus_negative_a"),
                            ("B+", "rhesus_positive_b"),
                            ("B-", "rhesus_negative_b"),
                            ("AB+", "rhesus_positive_ab"),
                            ("AB-", "rhesus_negative_ab"),
                            ("O+", "rhesus_positive_o"),
                            ("O-", "rhesus_negative_o"),
                        ],
                        max_length=3,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SicklingTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sickling_test",
                    models.CharField(
                        choices=[("yes", "positive"), ("no", "negative")],
                        max_length=3,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VDRL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vdrl",
                    models.CharField(
                        choices=[("yes", "positive"), ("no", "negative")],
                        max_length=3,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BloodWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blood_work_image_file",
                    models.FileField(upload_to=healthpass.models.user_directory_path),
                ),
                (
                    "blood_group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blood_group_blood_work",
                        to="healthpass.bloodgroup",
                    ),
                ),
                (
                    "hb_genotype",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hb_genotype_blood_work",
                        to="healthpass.hbgenotype",
                    ),
                ),
                (
                    "hepatitis_a",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hepatitis_a_blood_work",
                        to="healthpass.hepatitisa",
                    ),
                ),
                (
                    "hepatitis_b",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hepatitis_b_blood_work",
                        to="healthpass.hepatitisb",
                    ),
                ),
                (
                    "hiv",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hiv_blood_work",
                        to="healthpass.hiv",
                    ),
                ),
                (
                    "hpylori",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hpylori_blood_work",
                        to="healthpass.hpylori",
                    ),
                ),
                (
                    "malaria_parasite",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="malaria_parasite_blood_work",
                        to="healthpass.malariaparasite",
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_blood_work",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rhesus_antigen",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rhesus_antigen_blood_work",
                        to="healthpass.rhesusantigen",
                    ),
                ),
                (
                    "sickling_test",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sickling_test_blood_work",
                        to="healthpass.sicklingtest",
                    ),
                ),
                (
                    "vdrl",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vdrl_blood_work",
                        to="healthpass.vdrl",
                    ),
                ),
            ],
        ),
    ]
